import { MigrationInterface, QueryRunner } from "typeorm";

export class User1722313211416 implements MigrationInterface {
    name = 'User1722313211416'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "username" varchar2(255) NOT NULL, "email" varchar2(255) NOT NULL, "phone" varchar2(255), "password" varchar2(255) NOT NULL, "role_name" varchar2(255), "master_menu" varchar2(255), "picture" clob, "activated_at" timestamp, "gender" varchar2(255), "birth_place" varchar2(255), "birth_date" date, "religion" varchar2(255), "created_by" varchar2(255), "updated_by" varchar2(255), "deleted_by" varchar2(255), "created_at" timestamp, "updated_at" timestamp, "deleted_at" timestamp, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
