import { MigrationInterface, QueryRunner } from "typeorm";

export class Menu1723189529390 implements MigrationInterface {
    name = 'Menu1723189529390'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "menu_items" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "slug" varchar2(255), "icon" varchar2(255), "created_by" varchar2(255), "updated_by" varchar2(255), "deleted_by" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP, "deleted_at" timestamp, CONSTRAINT "PK_57e6188f929e5dc6919168620c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "master_menus" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "slug" varchar2(255), "menu_items" json, "created_by" varchar2(255), "updated_by" varchar2(255), "deleted_by" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP, "deleted_at" timestamp, CONSTRAINT "PK_fd5bcd348bdf9f9ec4b80376b80" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "master_menus"`);
        await queryRunner.query(`DROP TABLE "menu_items"`);
    }

}
