import { MigrationInterface, QueryRunner } from "typeorm";

export class UserNotification1723190048817 implements MigrationInterface {
    name = 'UserNotification1723190048817'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_notifications" ("id" number GENERATED BY DEFAULT AS IDENTITY, "username" varchar2(255), "is_read" number DEFAULT 0 NOT NULL, "title" varchar2(255), "description" clob, "type" varchar2(255), "link_path" varchar2(255), "link_params" varchar2(255), "created_by" varchar2(255), "updated_by" varchar2(255), "deleted_by" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP, "deleted_at" timestamp, CONSTRAINT "PK_569622b0fd6e6ab3661de985a2b" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "user_notifications"`);
    }

}
